### ISSUE TITLE
Mejora el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-sandrapinazo#1]
Buen trabajo @sandrapinazo 

Algunas pistas para mejorarlo:

- [x] Orgnaiza tus componentes en un carpeta 'components'
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Revisa el cierre de la etiqueta img
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Organiza estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by sandrapinazo** [comment]
Creo que ya está! al menos funciona.

**Comment by nasivuela** [comment]
Esto ya tiene muy buena pinta @sandrapinazo !!

Cierro el issue, pero te dejo algunas recomendaciones finales:

- Cuidado cuando instalas paquetes como node-sass, si no lo grabas en el package.json con `--save`, cuando otra persona arranca la aplicación tras hacer `npm install` esta falla por que falta algo.
- Mueve tus archivos de estilos juntos a sus componentes, cada oveja con su pareja.
- La lógica del handler de App `clickHandler` se puede simplificar con un `.map`. ¿Le das una intentona?

![](https://media.giphy.com/media/5xaOcLGvzHxDKjufnLW/giphy.gif)
